---
on:
  workflow_call:
    outputs:
      changed_files:
        value: ${{ jobs.pre-commit.outputs.changed_files }}
  pull_request:
  push:
    branches:
      - main

jobs:
  pre-commit:
    permissions: read-all
    runs-on: ubuntu-latest
    outputs:
      changed_files: ${{ steps.file_changes.outputs.files }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - uses: actions/setup-python@v5

      - name: Get changed files
        id: file_changes
        run: echo "diff=$(git diff --name-only origin/${{ github.base_ref }} ${{ github.sha }})" >> $GITHUB_OUTPUT

      - name: Cache pre-commit since we use pre-commit from container
        uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-3|${{ hashFiles('.pre-commit-config.yaml') }}

      - uses: pre-commit/action@v3.0.1
        with:
          extra_args: "--files ${{ steps.file_changes.outputs.files }}"
