---
on:
  workflow_call:
  pull_request:
  push:
    branches:
      - main

env:
  DIFF: $(git diff --name-only origin/${{ github.base_ref }} ${{ github.sha }})

jobs:
  pre-commit:
    permissions: read-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - uses: actions/setup-python@v5

      - name: Cache pre-commit since we use pre-commit from container
        uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-3|${{ hashFiles('.pre-commit-config.yaml') }}

      - uses: pre-commit/action@v3.0.1
        with:
          extra_args: "--files $DIFF"
